- proxy-kubernetes/argocd/apps/cluster-wide-apps/origin-cloudflared.yaml
LKE 上の origin 側 cloudflared の初期化に失敗する問題に対処するためのPR。
> `TUNNEL_ORIGIN_CERT` を設定して `origin-cloudflared-authorization-certificate` のマウントパスをずらす

- proxy-kubernetes/argocd/apps/cluster-wide-apps/origin-cloudflared.yaml
新しいバージョンでは [このPR](https://github.com/GiganticMinecraft/cloudflared-with-auto-dns-route/pull/9) が適用されています
> cloudflaredのイメージを更新する

- proxy-kubernetes/argocd/apps/root/crd-apps.yaml
prometheus operatorが入っていないため monitoring.coreos.com/v1/ServiceMonitor が無いと起こられてしまう
> fix: cert-managerの定義からprometheusの設定を削除する

- proxy-kubernetes/argocd/apps/cluster-wide-apps/descheduler/patch-schedule.yaml
Kustomize は Kustomization リソースの namespace で namespace の上書をするが、 patchesStrategicMerge が適用されるフェーズが先に実行されており、このフェーズにおいては、 kind/apiVersion/name/namespace でパッチ先を特定しているため、パッチに namespace まで書いておく必要があった
> fix: deschedulerのパッチの指定が足りないのを修正

- proxy-kubernetes/argocd/argocd-helm-chart-values.yaml
Reverts GiganticMinecraft/seichi_infra#155
AppProject リソースの destination はデプロイ先の制約だが、Application リソースの destination.namespace は [namespace-scoped なリソースで namespace が指定されていないもののデプロイに使われるのみ](https://github.com/argoproj/argo-cd/blob/8be24f577f127edd23119424f5125dcc73354f02/docs/operator-manual/application.yaml#L109)なので、具体的な namespace を指定するのが正しい。
> Revert "fix: root projectのdestination namespaceの制約を緩める"

- proxy-kubernetes/argocd/apps/seichi-gateway/cloudflared-mcserver-appset/application-set.yaml
> fix: seichi-gatewayのApplicationSetの名前がseichi-debug-gatewayのそれのものになっているのを修正する

- proxy-kubernetes/argocd-helm-chart-values.yaml
はやくもArgoCD Repo serverとserverのオートスケールが発火しているので、リソース許容値とオートスケールハッカのタイミングを変える
> Modify Argo CD resource request and autoscale

- proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
#262 の原因切り分けとして。
体感、プレイヤー数が多ければ多いほど新規接続がしにくくなる傾向があるので、怪しいパラメータを無効化してみるの巻。
本来`connection_throttle`のパラメータは同一IPからの接続リクエスト数を制限するものだが、上流にTCPShieldがいるのでワンチャン副作用を起こしている可能性がある。
問題なければ本番もやる。
> disable connection_throttle param on seichi-debug-gateway

- terraform/lke_cluster_argocd.tf
- terraform/lke_cluster_namespaces.tf
- terraform/lke_cluster_secrets.tf
- terraform/main.tf
> refactor: kubernetes/helmのresourceのproviderを明示的に指定する

- terraform/onp_cluster_argocd.tf
namespaceに依存しているものの、namespaceが既に作成されている場合新しいproxyにdependしないため、明示的な指定が必要
> fix: ArgoCD releaseからproxyへの明示的な依存を書く

- terraform/onp_cluster_secrets.tf
> fix: onp_cloudflared_tunnel_credentialを削除する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
> I've just rolled out an update to our proxies. With Proxy Protocol, before now we were also sending the hostname payload the RealIP plugin required to function, this means that player hostnames where server.com///<bunch of data> which caused forced hosts to not function correctly, therefore this has been fixed while using proxy protocol. However, this means if you for some reason still have the RealIP plugin installed, you will be getting a "Disconnected" error message. The fix is simply to remove the plugin, providing you have proxy protocol enabled.
Edit: RealIP is also known as TCPShield.jar
2022/03/30 TCPShield Official Discordより引用
https://discord.com/channels/820701684203257857/820705337958465546/958508761222352926
> remove tcpshield plugin

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
runAsが0なのにこいつがtrueだと矛盾して`ContainerConfigError`になってしまったので、問題が根本的に解決されるまではとりあえずRootで動かすしかなさそう
> Use root on prometheus

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/synology-csi-storageclass/kustomization.yaml
> refactor: synology-csi-storageclass で namespace.yml を管理しないようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/keda.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
KEDAを入れるとこんな感じでcronベースのscale to zeroができるようになるのでよさそうという話. related to https://github.com/GiganticMinecraft/seichi_infra/issues/417
ref. https://keda.sh/docs/2.7/concepts/scaling-deployments/
https://keda.sh/docs/2.7/scalers/cron/
```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
name: mc-server
namespace: mc-server
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: StatefulSets
name: mc-server # Mandatory. Must be in the same namespace as the ScaledObject
minReplicaCount:  0
maxReplicaCount:  1
triggers:
- type: cron
metadata:
timezone: Asia/Tokyo
start: 30 * * * *       # Every hour on the 30th minute
end: 45 * * * *         # Every hour on the 45th minute
desiredReplicas: "0"
```
> Add KEDA for scale to zero requirement based on schedule

- seichi-onp-k8s/manifests/seichi-kubernetes/argocd-helm-chart-values.yaml
現状`app controller`と`dex`は単一のPodで動いており、pdbを不用意に仕掛けるとかえって副作用があるため削除する。具体的にはkubectl drainでノードをシャットダウンする場合などにこれらのPodを退役できずエラーになったりする。
一方で、pdbを使うにはPodを少なくとも2台以上で構成するべきであるが、dexはインメモリストアに認証情報を持たせるためあまり水平スケールのメリットがなく、app controllerについても複数台構成の場合シャードが必要なので、シングル構成のほうが考慮事項が少なくて楽である。加えて瞬間的な停止によるユーザーインパクトはまず無いことから、わざわざ台数を増やしてまでpdbを増やす意味がなさそうという結論に至った。
ref. https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#scaling-up
> Remove pdb from single components of ArgoCD

- seichi-onp-k8s/manifests/seichi-kubernetes/README.md
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
この変更ではKubernetesのservice nameで指定しているが、VM側にいるデバッグサーバーではLoadBalancderで指定したservice segmentのIPアドレスを指定する必要がある。
そのうちKubernetes側に全サーバーが集約されるようになったらLBはClusterIPに変更して良さそう。
Compose側での変更が適用できるタイミングでこれも入れる。
> use k8s internal redis

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
いつぞやからgrafanaが以下のエラーで起動しなくなってたので修正
`Datasource provisioning error: datasource.yaml config is invalid. Only one datasource per organization can be marked as default`
> fix: grafanaのdefaultではないdatasourceを明示する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/newrelic.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
- terraform/main.tf
- terraform/onp_cluster_namespaces.tf
- terraform/onp_cluster_secrets.tf
よくわからんのでとりあえずk8s integrationのinstall wizardをデフォルト値で進めたら出てきたhelm installコマンドをベースに錬成。
追加オプションは以下がデフォルト選択
Pixie uses eBPF to automatically detect any HTTP-based services in this cluster and gather data. For even deeper insights, you can add language agents to individual services.
install wizardで出たベースとなったコマンドはこんな感じ
```bash
function ver { printf "%03d%03d" $(echo "$1" | tr '.' ' '); } && \
K8S_VERSION=$(kubectl version --short 2>&1 | grep 'Server Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $1"."$2; }') && \
if [[ $(ver $K8S_VERSION) -lt $(ver "1.25") ]]; then KSM_IMAGE_VERSION="v2.6.0"; else KSM_IMAGE_VERSION="v2.7.0"; fi && \
helm repo add newrelic https://helm-charts.newrelic.com && helm repo update && \
kubectl create namespace newrelic ; helm upgrade --install newrelic-bundle …
```
> feat: add newrelic agents

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- terraform/cloudflare_network_admin_services.tf
- terraform/github_teams.tf
PDUの管理パネルをCloudflare-ZeroTrust経由で公開する(許可メンバーはリモートでproxmoxホストの電源制御が可能になる)
関連:
https://github.com/GiganticMinecraft/teams/pull/19
> feat: add raritan(PDU)-web-panel

- terraform/cloudflare_dns_records.tf
https://github.com/GiganticMinecraft/CommandReference/issues/5 にて、 CommandReference に対し `cmd.seichi.click` というカスタムドメインを割り当てました。
https://docs.github.com/ja/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
> CommandReferenceのカスタムドメインへのDNSを設定

- terraform/cloudflare_page_projects.tf
https://discord.com/channels/237758724121427969/959300385883967498/1087151721345724466
https://discord.com/channels/237758724121427969/959300385883967498/1087288362458685450
上記のDiscordリンクのように、Cloudflare側でビルドをしてデプロイをする形だと、Cloudflareを直接開くことができる人でないとログを確認することができない。いちいち、ビルドが失敗するたびにログをスクショしてもらうのは大変。
よって、Cloudflare側でビルドをするのではなく、GitHub Actions側でビルドをして、Cloudflare側にその生成物をアップロードする形にすることで、これを回避することができる。
> fix: Cloudflareによって自動的にPagesにデプロイするのを止める

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/gachadata-server/deployment.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/gachadata-server/service.yaml
[gachadata-server](https://github.com/GiganticMinecraft/gachadata-server) を追加しました。
gachadata-serverは[SeichiAssistのissue#2178](https://github.com/GiganticMinecraft/SeichiAssist/issues/2178) を解決するために作られたサーバーで、`seichiassist`データベースから、`gachadata.sql`のダンプファイルをダウンロードすることができます
> gachadata-serverを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/gachadata-server/deployment.yaml
MySQLユーザーが`mc-server`だと思っていたら`mcserver`っぽいので直しました。
(そもそもあってますか...?)
下の2つを参考にしました
https://github.com/GiganticMinecraft/seichi_infra/blob/8d1d53d69989cf71a70a6ac2570ba06f53cc20a3/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichi-game-data-server/deployment.yaml
https://github.com/GiganticMinecraft/seichi_infra/blob/8d1d53d69989cf71a70a6ac2570ba06f53cc20a3/seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichi-game-data-server/configmap.yaml
> fix: mysql_userをmcserverにする

- seichi-onp-k8s/cluster-boot-up/ansible/roles/00-wait-to-host-reachable/tasks/main.yaml
> feat: kubeadmの実行ファイルが存在するまでansibleを待たせる

- seichi-onp-k8s/cluster-boot-up/README.md
- #1280 でやるって言ってたドキュメント更新
- 最近やったクラスタ再構築時に足らなかった手順の追加
> docs: ansible対応部分を削除,terraformの初回設定追加,初期パスワード変更追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/stateful-set.yaml
- terraform/onp_cluster_minecraft_secrets.tf
https://github.com/GiganticMinecraft/seichi_infra/pull/1397#pullrequestreview-1723718869
この返信を参考に、PRごとにデバッグサーバーを立ち上げる部分のinitContainerにmod-downloaderを追加しました
> PRごとにをデバッグサーバーを立ち上げるときのinitContainersにmod-downloaderを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/stateful-set.yaml
- terraform/onp_cluster_minecraft_secrets.tf
https://discord.com/channels/237758724121427969/959299646725951580/1175598364344205412
`MINIO_DEBUG_ACCESS_KEY`が見つけられないというエラーが出ていたので、すでにminioの`key`と`secret`が定義された`onp_cluster_secrets.tf`から取得するように修正しました。
`mcserver--common--config-secrets`から`key`と`secret`が取得できなかった原因が分からなくて、とりあえずminioのアクセス情報が定義されているところがあったのでそこから取得するようにしてみましたが、これで動くのかどうかはわかっていないのでそもそも方向性が正しいかを見てほしいです。
> minioの`access-key`と`access-secret`を`onp_cluster_secrets.tf`の`minio-access-secret`から取る

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
検証環境として、最低限整地ワールドがないといけないので作成するコマンドがサーバー起動時に実行されるようにしました
https://docker-minecraft-server.readthedocs.io/en/latest/configuration/auto-rcon-commands/
> ワールドを作成するコマンドが起動時に実行されるようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
https://docker-minecraft-server.readthedocs.io/en/latest/configuration/auto-rcon-commands/
に「When declaring several commands within a compose file environment variable, it's easiest to use YAML's |- [block style indicator](https://yaml-multiline.info/).」と書かれていました
> fix: valueに改行コードが含まれないようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
ワールドが作成される前に設定されていたので、有効になっていなかった
> fix: ワールドが作成されてからkeepInventoryを有効にする　

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
https://discord.com/channels/237758724121427969/1185938074434289795
これを実現するためのプラグインで、設定ファイルが必要でした
> Elytraプラグインとconfigを入れる

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
本番サーバーのメインワールドは`world_2`で、プラグイン側でワールド名をで判定しているので合わせる必要がありました
> メインワールド名を本番環境とあわせる

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/https-exits.yaml
- terraform/cloudflare_network_admin_services.tf
- terraform/github_teams.tf
> feat: proxmox-monとzabbix追加、IP修正

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/lobby-server.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/plugin-config.yaml
OriginSpawnがスポーン地点を固定する機能を持っているので、ロビーサーバーにOriginSpawnを追加しました。
OriginSpawnのconfigはメインサーバーのものとは違うので、ロビーサーバー用のConfigMapを追加しました
> ロビーサーバーにOriginSpawnを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
https://worldguard.enginehub.org/en/latest/blacklist/index.html  では`Blacklist.txt`ではなく`blacklist.txt`というファイル名を指定している
> WorldGuardの設定ファイル名の間違いを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
プラグインの中身が単純 + まともに動いていなかった のでSeichiAssistに同様の機能を追加しました。のでStreamClockを削除します
> streamclockを削除

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
> ネザーゲートを使用禁止にする

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
SeichiAssistのワールド内マイグレーションをするときにワールドのアンロードを失敗するので、SeichiAssistと依存するプラグイン以外を無効化しました
後で戻します
> SeichiAssist以外のプラグインを一旦無効化する

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
増やすことにした経緯:
- SeichiAssistが行うワールドマイグレーションを走らせると`OutOfMemoryError`が発生するようになった
- [Paper公式が推奨しているJVMオプション](https://docs.papermc.io/paper/aikars-flags)を追加した
- `OutOfMemoryError`は発生しなくなったが、Grafanaを見るとメモリが限界値に張り付いた後に落ちるようになった
- メモリが足りていないことは明らかなので、試しに増やしたい(少し増やせば足りるのか、根本的に処理を見直さないといけないのか見たい(できれば処理の書き直しはしたくない))
> デバッグサーバーのメモリ量を増やす

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
global保護でブロックの設置破壊ができるようになってしまっている
> feat: global保護にunchamaさんをmemberとして追加するようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
https://x.com/tsukkkkkun/status/1767035874607522232
> オンプレk8sでクラスタ吹っ飛び前提のPVのバックアップリストアの仕組みを考えてるんですが、ダイナミックプロビジョンな仕組み経由でディスク側の識別情報(名前とか)を固定化するのは難しそうなのでゴリゴリに環境依存なPVを書くかみたいなお気持ちになってる。(要約:運用設計むずかしい)
そもそもPVすら書いてない気がする。
> minecraft-server-dataは直接LUNをマウント

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/seichiassist-downloader.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
前に1.18用の固定デバッグサーバーはSeichiAssistのダウンロードだけ決め打ちしていたので、最新のリリースを持ってくるやつをかきました
> feat: seichiassist-downloaderをdebug-s1に追加

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
- ArgoCDのエラーを見るとcommandは配列形式で指定されるべきらしいのでそのように修正しました
- 同じくエラーによるとmountPathは重複してはいけないようなので修正(とはいえ`/data`ディレクトリがすでにマウントされていて、`/data/plugins`ディレクトリは`/data`ディレクトリに内包されるので、これが許されるかどうかは実行してみないとわからない)
> seichiassist-downlaoderのapplyに失敗するのを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/event-source.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
Argo WorkflowsとArgo Eventsを使用して、SeichiAssistのpushがあったことをwebhookで検知してminioにアップロードするための定義を追加しました。
> seichiassistをminioにアップロードするためのワークフローを定義

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
`1_18`というブランチ名が数字として解釈されていることが原因ぽいので修正しました
> fix: ブランチ名をエスケープする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/argo-workflows-reverse-proxy.yaml
`Deployment` の定義としては不十分な定義だったので直しました
> fix: argo workflows のリバースプロキシの定義を直す

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/lobby-server.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
一定期間経過後にLuckParamsのリンクが無効化されるようなので、minioからダウンロードするために削除しました
> chore: LuckParamsのダウンロードリンクを消す

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/event-bus.yaml
ArgoEvents の EventSource と Sensor のやり取りには EventBus が定義されている必要があるようですが、定義していなかったので定義しました。
[ArgoWorkflows 上の status](https://argo-workflows.onp-k8s.admin.seichi.click/event-sources/seichi-minecraft/seichiassist-downloader?tab=manifest) で `EventBusNotFound` と表示されているので、定義を追加しました。
[このページ](https://argoproj.github.io/argo-events/eventbus/stan/)を参考にしました
> ArgoEvents が Webhook リクエストを正しく受け付けないのを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/event-source.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
EventBus の `name` を `default` 以外にするときは Sensor と EventSource の定義に `eventBusName` を定義しないといけないそうなので追加しました。
https://argoproj.github.io/argo-events/eventbus/eventbus/
> EventSource と Sensor に `eventBusName` を指定する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
マージは PR 作成日の 1day to reset が終了した後. ( Approve はその前に出してもらって構いません)
> deps: bump 1day-to-reset

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/bgp-peering-policy-v2.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/loadlbalancer-ip-pool.yaml
[公式ドキュメント](https://docs.cilium.io/en/stable/network/bgp-control-plane/bgp-control-plane-v2/) によれば、`CiliumBGPPeeringPolicy` と `CiliumBGPClusterConfig` が同時に存在し、Cilium エージェントが両方の `nodeSelector` にマッチする場合、 `CiliumBGPPeeringPolicy` が優先されるそうです。
ほか、[Upgrade Guide](https://docs.cilium.io/en/stable/operations/upgrade/) によると、
1. `CiliumLoadBalancerIPPool.spec.allowFirstLastIPs` のデフォルト値が `yes` に変更されました。
つまり、明示的に設定を変更しない限り、IP プールの最初と最後の IP アドレスも割り当て可能になります。
以前の動作（最初と最後の IP アドレスは割り当て不可）に依存している場合は、アップグレード前に IP プールの設定で `allowFirstLastIPs: no` を明示的に設定する必要があります。
2. `CiliumLoadBalancerIPPool.spec.cidrs` フィールドは v1.15 で非推奨となり、 `CiliumLoadBalancerIPPool.spec.blocks` が代わりに推奨されるようになりました。
v1.15 の時点では両方のフィールドは同じ動作をしますが、`cidrs` フィールドは v1.16 で削除されます。
アップグレード前に、IP プールの設定を `cidrs` から `blocks` に更新してください。
> migrate bgp control plane v2 before upgrading cilium to 1.16

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/loadlbalancer-ip-pool.yaml
`Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from config resource: .spec.allowFirstLastIPs: expected string, got &value.valueUnstructured{Value:true}`
> fix: ここは実はStringらしい

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/bgp-peering-policy-v2.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/loadlbalancer-ip-pool.yaml
Reverts GiganticMinecraft/seichi_infra#2133
> Revert "Revert cilium-network-configs"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
`E: The update command takes no arguments` と言われていたので追加しました
> fix: download-seichiassist の apt-get update に -y を追加

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
Reverts GiganticMinecraft/seichi_infra#2208
関係なかったので Revert します
> Revert "fix: download-seichiassist の apt-get update に -y を追加"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
`mc cp` コマンドではアップロードするオブジェクト名まで指定する必要がないらしいです
> fix: minio にファイルをコピーするコマンドが間違っているのを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/bungee-portals-config.yaml
ロビーサーバーにある最初にスポーンするワールドの名前は「world」ではなくて「world_2」
> fix: BungeePortalのポータル設定のうち、ポータルが設置されているワールドが間違っているので修正

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/mariadb/mariadb.yaml
他プラグイン用のDBも作るので、shの引数はパイプにしています
> LuckPerms用のDBを作成するSQLクエリをMariaDBのinitContainerで作成する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite.yaml
ref: https://github.com/m1sk9/babyrite/issues/220
`serde_yaml` 非推奨に伴い, serde がメンテナンスしている `toml` ( `serde_toml` ) に切り替えました. 
v0.11.0 はサポートを打ち切っています.
https://babyrite.m1sk9.dev/changelog.html#v0120
> deps: bump babyrite v0.12.0

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite.yaml
https://github.com/m1sk9/babyrite/blob/7aa11624bd8def06d903c72ba98501316113f7e8/Dockerfile#L8-L12
v0.13.0 で Docker Image で使用する Runner Image を `gcr.io/distroless/cc-debian12` に変更した際, 実行ファイルをルートディレクトリ上に配置するよう Dockerfile を書き換えたため, `babyrite-config-volume` のパスが不正になっていました
> fix: `babyrite-config-volume` mount path

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/deployment.yaml
内部で使用しているBungeecordをダウンロードするPaperMCのAPIが変更され、サーバが起動しなくなってしまったため、ひとまずitzg/bungeecordのバージョン更新を試みる。
> feat: update itzg/bungeecord from `java17-2022.4.1` to `java17-2024.6.0`

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/deployment.yaml
`java21-2024.6.0`だと、古いAPIを参照しているため、ひとまずリリース番号を外す
> fix: use `itzg/mc-proxy:java21`

- docker-images/mcservers/debug/seichi-servers/base-images/1_18_2/Dockerfile
Reverts GiganticMinecraft/seichi_infra#2388
`mcserver--debug--pr-2115` で paper の jar ファイルを取得できない原因の切り分けのために、一旦 revert します
> Revert "chore(deps): update ghcr.io/giganticminecraft/seichi_minecraft_server_base:1.0.0-java17-jdk docker digest to 627736a"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
unchamaさんをメインワールドや第2整地の`__global__`保護のメンバーに追加するコマンドをサーバ起動時に実行するが、プレイヤー名をUUIDに変換する処理が行えない（*）ので、UUIDを直接指定する
*: Failed to add new members: Unable to resolve the names
> fix: use UUID for WG member

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
AutoMessageの設定ファイル中の`random`は、時間が来たときにメッセージを表示するかどうかをランダムに決めるかどうかを示すものであり、どのメッセージを表示させるかをランダムにするものではないっぽい。
> fix: set random false in AutoMessage config

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
Reverts #2440.
See: https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/192
> `/hub`コマンドを`/server`コマンドのエイリアスとして設定することはできなかったのでrevertする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
すみません、BungeeHubCommandではなくてBungeeKickの設定を編集していました..。
ref. #2443, [GiganticMinecraft/SeichiAssist-ExternalLibs#192](https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/192)
> fix: fix hub name in BungeeHubCommand

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
https://github.com/mariadb-operator/mariadb-operator/blob/a0bc88ae6ca26e85f5183b87bf144bb2438cff99/docs/CONFIGURATION.md?plain=1#L30 
mcserver--debug-s1 から mariadb に接続できない問題の改善を試みています
> fix: mariadb の設定に bind-address の設定を追加

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
https://github.com/mariadb-operator/mariadb-operator/blob/a0bc88ae6ca26e85f5183b87bf144bb2438cff99/docs/TLS.md#mariadb-configuration
> chore: seichi-debug-minecraft の mariadb の tsl を無効化する

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
`initContainer` でした
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#resourcerequirements
> fix: initContainers -> initContianer

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#mariadbspec
`initContainers` でした
> fix: debug-minecraft の mariadb の initContainer 指定を直す

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
https://github.com/mariadb-operator/mariadb-operator/blob/a0bc88ae6ca26e85f5183b87bf144bb2438cff99/examples/manifests/mariadb_init_and_sidecar.yaml#L49 によるとデフォルトで全てのボリュームがマウントされているらしい
> fix: volumeMounts を削除

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/deployment.yaml
github.com の HTML を .jar って名前送りつけてごめん (2)
(ダウンロード先のリンクを修正します)
> fix: Fix download link 

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
スタイル修正ついでに "[wawawa忘れ物](https://github.com/unchama/AdvAfkKick/commit/39005323a2c88259fcf5689756e10f163c173256)" と "さて...整地の休憩ついでに 整地するか！" を追加
> fix: Fix motd style

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
https://docs.papermc.io/paper/reference/server-properties
1.12.2では、spawn-protection は無効化されている。
> fix: disable spawn-protection

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/luckperms-permission-configs.yaml
`admin`グループに所属するメンバーが`default`グループにも属していると、`deny`が優先されるので、一般ユーザが行えないように指定されている操作も行えなくなってしまう（そのためのweight指定と`*`許可だと思うんですけどね、効かないらしい）
> fix: members of admin team should not belong to default permission group

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/workflow-sa.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
とりあえずバックアップだけ。リストアはまだ。
- 実行トリガーはCronWorkflowを使う
- トリガー実行後の流れ
- 何らかの方法でバックアップ対象マイクラサーバーのscalingを0にする
- kubectl apply or patchを使用
- kedaを使っていい感じにできないかなと思ったが、ScaledObjectをkubectl applyするというpatchと何が違うんですかみたいな感じだった
- proxmox-backup-clientでバックアップを取得する
- 終わったら何らかの方法でバックアップ対象マイクラサーバーのscalingを1にする
- kubectl apply or patchを使用
> デバッグサーバにproxmox-backup-clientを使用した定期バックアップの仕組みを構築する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/redisbungee-redis.yaml
https://github.com/bitnami/charts/pull/32117 によると、2.10.0 から `usePasswordFiles` のデフォルト値が `true` になったらしく、その影響か redis が起動しなくなったので一度 `false` にしてみます
> fix: redisbungee-redis の auth.usePasswordFiles を false にする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/redisbungee-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redis/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redis/redisbungee-redis.yaml
Reverts GiganticMinecraft/seichi_infra#2572
https://github.com/GiganticMinecraft/seichi_infra/pull/2577 これでも上がってこず、原因がわからないので一度 revert します
> Revert "chore(deps): update registry-1.docker.io/bitnamicharts/redis docker tag to v20.10.0"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/custom-enchantments-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/dynmap-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/luckperms-permission-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/mcserver-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/seichiassist-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/worldguard-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/argo-workflows-restore.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/multiverse-portals-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/ops-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/plugin-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/service-monitor.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/workflow-sa.yaml
- terraform/onp_cluster_minecraft_secrets.tf
`debug-s1` と `debug-pr-2115-s1` をもとに追加しました
> feat: s1 用の定義を追加

- renovate.json
エスケープが足りていなく、json としてパースした後に正しい正規表現となっていないため、 mcserver_base_image が更新されていない？
> fix: renovate が mcserver_base_image を更新しないのを修正

- .github/workflows/build_mcserver_base_images.yaml
文脈: https://discord.com/channels/237758724121427969/959299646725951580/1351832304200319036
日付を含むイメージタグを使用すると、そのタグを持つイメージ自体は更新されないので、renovate に更新が検知されない
> fix: mcserver_base_image_tag で使用するタグをバージョン固定のものに変更する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
> fix: s1 の coreprotect で使用する mysql のポートの環境変数を文字列として渡す

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
`/plugins` ディレクトリには上位イメージですでに config ファイルが含まれているが、そこに mod-downloader のボリュームをマウントすることでデータが消えている？
> fix: mod-downloader から配置されるプラグインを /data/plugins に配置する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
base-server-image 側ですでにダウンロードされている
> chore: jmx-exporter-downloader を s1 の定義から削除

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
> fix: redisbungge/bunmgeesemaphore の接続先情報が間違っているのを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
ArgoCD 上で out of sync になり続けていて、Diff を見ると差分が出ているのでその影響？
関係なさそうだったら revert します
> fix: s1 の volumeClaimTemplates に apiVersion と kind を指定

- renovate.json
renovate は `:sha-410bcbb` のようなバージョニングのイメージを標準だと検知してくれないようで、GiganticMinecraft のイメージはこのようなバージョニングを持つものが多いので検知されるようにしました。
> chore: renovate に packageName:sha- 形式のイメージを検知させる

- renovate.json
Reverts GiganticMinecraft/seichi_infra#2715
想定していない PR が投げられてしまったので一旦 revert します  https://github.com/GiganticMinecraft/seichi_infra/pull/2716
> Revert "chore: renovate に packageName:sha- 形式のイメージを検知させる"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
Modify SyncWindows settings to manage selfHeal execution times, preventing interference during scheduled backups.
> Adjust SyncWindows for Minecraft server resources

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--votelistener/stateful-set.yaml
> chore: votelistener から persistentVolumeClaim の定義を取り除く

- docker-images/mcservers/base-server-image/common-plugin-list.ini
- docker-images/mcservers/production/lobby/additional-plugin-list.ini
base-image を使用するすべてのマインクラフトサーバーが必要としているプラグインではない
> base-server-image の additional-plugin-list から ViaBackwards と ViaVersion を 削除

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/lobby-server.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-lobby/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/bgp-peering-policy.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--votelistener/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--votelistener/stateful-set.yaml
tailscaleのadvertise-routeされたPodIP or ServiceIPから触りに行く想定
> Add jmx-remote configuration to Minecraft server manifests

- renovate.json
https://docs.renovatebot.com/configuration-options/#matchpackagenames
`matchPackagePatterns`という設定は存在せず、やりたいことは`matchPackageNames`という名前だと思われる
> Renovateの設定中のキー指定が誤っているので修正

- .github/workflows/shellcheck.yaml
action-shellcheck のバージョンタグには v というプレフィックスがついているが、ワークフローのコメントに記載されていないので、renovateがバージョン検知に失敗している。
https://github.com/reviewdog/action-shellcheck/releases
> chore: fix shellcheck action versioning

- docker-images/mcservers/production/seichi-servers/common-image/additional-plugin-configs/region-grid-fitter/config.yml
1.12.2のs1からs7ですべて同じ設定になっていることを確認済み。
> fix: 1グリッドの1辺は15ブロックなので修正

- .github/workflows/build_mcserver_images.yaml
1.0.0タグ付きの`common`イメージを作るために、一旦強制的にビルドさせる
> chore: force build `ghcr.io/giganticminecraft/seichi_minecraft_server_production_common`

- docker-images/mcservers/production/seichi-servers/common-image/additional-plugin-configs/dynmap/configuration.txt
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/dynmap-nginx-conf--s1.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- Webページのタイトル内に含まれるサーバ名の設定ができていなかったので修正
- DynMapが公開している「自分でWebサーバを立てるとき用の設定」ページに記載されたnginx.confを見て、必要そうなものを追加
- `Web files are not matched with plugin version: All files need to be same version (3.7-SNAPSHOT-948) - try refreshing browser cache (shift-reload)`と言われたので、1.12.2時代に生成されたDynMapのWebコンテンツを一旦削除する
> fix: DynMap周りを調整する

- docker-images/mcservers/base-server-image/common-minecraft-server-configs/paper.yml
Timings V2 はすでにメンテナンスが終了しており， Paper は LuckPerms の開発者が開発・保守しているプロファイリングプラグインである Spark への移行を推奨している．
1.21 以降の Paper には Spark が内蔵されているが，1.18.2 には内蔵されていないため別で Spark を導入する必要がある．
このプルリクエストでは Timings の機能を無力化する．
https://docs.papermc.io/paper/profiling/#spark
> feat: Timings v2 を廃止し，Spark に移行する

- docker-images/mcservers/production/lobby/additional-plugin-configs/AntiProxy/config.yml
> fix: AntiProxyによるBlacklistのメッセージを日本語にする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
> create Pod mcserver--one-day-to-reset-0 in StatefulSet mcserver--one-day-to-reset failed error: Pod "mcserver--one-day-to-reset-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "mod-downloader-volume", spec.initContainers[0].volumeMounts[0].name: Not found: "mod-downloader-volume"]
s1とかは`.spec.template.spec`以下（=今回の修正後）に`volume`の定義があるので、そちらに合わせました。
（kagawaがなぜ`.spec.template`に`volume`の定義がある状態で動いているのかよくわからないですけど）
> 1dayサーバの定義において、volumeの定義位置がずれているのを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config.yaml
```
Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
```
というエラーを吐いていて、怪しそうなので
> fix: bungeecord-config からコメントアウトされているものを削除
