GiganticMinecraft/seichi_infra

- terraform/lke_cluster_secrets.tf
- terraform/main.tf
> Access service tokenをLKEのSecretとして入れる

- terraform/lke_cluster_secrets.tf
- terraform/main.tf
Reverts GiganticMinecraft/seichi_infra#10
> Revert "Revert "Access service tokenをLKEのSecretとして入れる""

- util-scripts/setup/docker-ce-and-compose.sh
> fix : docker-ce-and-compose.shが環境によってこける

- proxy-kubernetes/production-k8s-manifests/bungeecord-deployment.yaml
> prod-bungeecord's replicas 0 > 2

- proxy-kubernetes/clusterwide-k8s-manifests/origin-cloudflared/origin-cloudflared.yaml
> `origin-cloudflared`の`TUNNEL_NAME`を明示的に指定する

- proxy-kubernetes/production-k8s-manifests/cloudflared-votelistener-deployment.yaml
- proxy-kubernetes/production-k8s-manifests/cloudflared-votelistener-service.yaml
- proxy-kubernetes/production-k8s-manifests/kustomization.yaml
> votelisterパケット受付用のcloudflaredとloadbalancerを生やす

- diagrams/unchama-home-infra.drawio.svg
> docs: うんちゃま家の簡易物理ネットワーク図を追加

- terraform/github_repositories.tf
> github_branch_protectionのリソース名を修正

- proxy-kubernetes/README.md
- proxy-kubernetes/argocd-apps/argocd.yaml
This PR fixes #57.
多分鍵が渡ってなかったのでsealed-secretで渡すようにしてみた
> Fix ArgoCD's SSO

- terraform/github_repositories.tf
Reverts GiganticMinecraft/seichi_infra#68
> Revert "管理者がseichi_infra_mainに強制マージできるように"

- proxy-kubernetes/argocd-apps/argo-cd.yaml
> fix: valuesの先頭にコメントを書かないように

- proxy-kubernetes/argocd-apps/argo-cd.yaml
Reverts GiganticMinecraft/seichi_infra#97
> Revert "debug: ブートストラップ後のArgoCDをplainなものにしてみる"

- proxy-kubernetes/argocd/apps/argocd/argo-cd.yaml
- proxy-kubernetes/argocd/apps/argocd/roots.yaml
- proxy-kubernetes/argocd/argocd-bootstrapping.yaml
> fix: ArgoCDにroot projectを追加する

- terraform/lke_cluster_namespaces.tf
- terraform/lke_cluster_secrets.tf
- terraform/main.tf
> LKEクラスタのsecretとしてCloudflareとArgoCD GitHub連携に関する認証情報を定義する

- proxy-kubernetes/argocd/apps/root/app-of-apps.yaml
- proxy-kubernetes/argocd/apps/root/projects.yaml
- terraform/lke_cluster_namespaces.tf
- terraform/lke_cluster_secrets.tf
> Add app of cluster wide apps

- proxy-kubernetes/argocd/apps/cluster-wide-apps/kustomization.yaml
- proxy-kubernetes/argocd/apps/cluster-wide-apps/origin-cloudflared.yaml
これで https://argocd.bungee-proxy-public.seichi.click/ とかが見えるようになるはず
Closes #128.
> origin-cloudflaredをcluster-wide-appsに追加する

- terraform/lke_cluster_argocd.tf
これでargocdのサービス名が `argo-cd-argocd-server` とかではなく `argocd-server` になってくれるはず…
> refactor: argocdのhelm_releaseのnameをargo-cdからargocdに

- README.md
> fix In line code

- proxy-kubernetes/argocd/apps/root/apps.yaml
- proxy-kubernetes/argocd/apps/root/projects.yaml
- proxy-kubernetes/argocd/apps/seichi-debug-dateway/cloudflared-mcserver-appset/application-set.yaml
- proxy-kubernetes/argocd/apps/seichi-gateway/cloudflared-mcserver-appset/application-set.yaml
各々のnamespaceに入れてもArgoCDに認識してもらえなかった
> fix: ApplicationSet も argocd namespace に入れる

- proxy-kubernetes/argocd/apps/seichi-debug-gateway/bungeecord/deployment.yaml
- proxy-kubernetes/argocd/apps/seichi-gateway/bungeecord/deployment.yaml
Good bye GHA kubectl apply
TODO: Somehow tidy up the manifests
> move bungeecord deployment to argocd

- proxy-kubernetes/README.md
> docs: クラスタブートストラップについて書く

- proxy-kubernetes/argocd-helm-chart-values.yaml
Addresses https://github.com/GiganticMinecraft/seichi_infra/issues/192
リソースの制限値についてはメトリクスにらめっこしながら決めていく
> Add redundancy to ArgoCD

- terraform/cloudflare_network_debug_proxy_to_op.tf
Reverts GiganticMinecraft/seichi_infra#203
> Revert "debug: regen-token"

- proxy-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-config-patch.yaml
@Megumiso (2022/04/02 6:28 AM JST)
見えるの自体はいいんですけど、これいらないので消しちゃっていいかもです
とのこと
> feat!: tm1 サーバーを削除する

- proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-deployment-patch.yaml
- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
これはBungeeCordのpod再起動をトリガーしないはず
> feat: #222 をbaseにまで適用する

- proxy-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-config-patch.yaml
- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/configs/bungeecord-config.yaml
`/hub` コマンド復活祭
これで本番のプロキシが再起動されるはずなので瞬断についてアナウンス済み。0:10前後にマージします。
> feat: bungeehubcommand.hubを本番側のdefaultグループにも付与する

- proxy-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-config-patch.yaml
> feat!: mcserver--eve02を削除

- README.md
- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
@inductor initContainer周りの指定が適切かを見てほしいです
@sakarush ライセンス周りの更新が適切かを見てほしいです
Blocked by: https://github.com/GiganticMinecraft/branding/pull/1
> サーバーアイコンを設定するように

- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
> fix: wgetの引数を修正

- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
> fix: readiness probeの代わりにstartup probeを使う

- proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
Reverts GiganticMinecraft/seichi_infra#243
> Revert "debug: bungeecordからstartup probe消してみる"

- terraform/main.tf
> feat: logdna-agentの動作に必要なterraform variableを定義する

- seichi-onp-k8s/cluster-boot-up/scripts/nodes/k8s-node-setup.sh
Ref. https://prometheus-operator.dev/docs/kube-prometheus-on-kubeadm/#kubeadm-pre-requisites
> Expose Control Plane Metrics

- terraform/onp_cluster_secrets.tf
> feat: add secrets

- terraform/lke_cluster_secrets.tf
Reverts GiganticMinecraft/seichi_infra#306
> Revert "fix: cloudflared_tunnel_credentialを削除"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
> Permit Metal LB namespace to the project

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
CRDは再作成にしないとこけるエラーがある
https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1030198014
> fix prometheus crd

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/cilium.yaml
After https://github.com/GiganticMinecraft/seichi_infra/pull/320
> Fix cilium chart

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
さんこう
https://github.com/prometheus-operator/prometheus-operator/issues/2155#issuecomment-441002864
> Let prometheus scrape all namespaced metrics

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
> use namespaces instad

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/cilium.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/argocd-helm-chart-values.yaml
> add labels

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/synology-csi-driver.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/csi-snapshotter-crd/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/csi-snapshotter/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/synology-csi-storageclass/storageclass.yaml
- terraform/main.tf
- terraform/onp_cluster_namespaces.tf
- terraform/onp_cluster_secrets.tf
これ以外は自動化できた気がする
```sh
config_file=/tmp/config.yaml
cat > $config_file <<EOF
---
clients:
- host: 192.168.16.240
port: 5000
https: false
username: kubernetes-csi
password: password
EOF
kubectl create secret -n synology-csi generic client-info-secret --from-file="$config_file"
```
> almost automate csi driver installation

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
sentryは置いといてひとまずkube-prometheus-stackだけ
とりあえずこれで動くと思うけど、どうしましょうね
参考: https://github.com/SynologyOpenSource/synology-csi/issues/30
> fix: unable to access provisioned storage

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
Grafanaもファイルシステムに書き込めんって言いだしてるのでこうしていく
> run grafana as root for pvc

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/prometheus-operator.yaml
> delete startup-config on grafana

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-app-resources/sentry.yaml
> disable kafka and zookeeper

- seichi-onp-k8s/manifests/seichi-kubernetes/argocd-helm-chart-values.yaml
> Increase AppSet Controller memory limit

- .github/workflows/terraform_apply.yaml
- .github/workflows/terraform_pr.yaml
> fix: 常に tf apply するように

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
> fix approject

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/sentry.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/synology-csi-storageclass/storageclass.yaml
これを入れるとsecurtyContext周りがなおるっぽい
```diff
-  fsType: 'ext4'
+  csi.storage.k8s.io/fstype: ext4
```
> Fix fstype

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/loki.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/argocd-helm-chart-values.yaml
- Add cascade deletion on Prometheus Operator
- Remove resource limits on ArgoCD controllers
> Modify param

- seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/service-bungeecord-metrics.yaml
Prometheus Operatorにスクレイプしてもらうゾ
> Fix ServiceMonitor label

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/reloader/kustomization.yaml
> fix: reloaderの参照にref=を入れる

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/keda.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/loki.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/sentry-kafka.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/sentry.yaml
PrometheusとSentryはDiffが出て厄介（特にSentryは現状破壊的変更になってしまう）のでそれ以外にself healを入れておく
> Add Self heal on app resources

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/tetragon.yaml
FalcoはなんかMetricsがうまく取れなくてぴえんだった。
実験的ではあるがCiliumシリーズでまとめてTetragonを入れてみるわよ
> Add tetragon to hook sus events

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- terraform/cloudflare_page_rules.tf
06/06 4:30とかにマージしたい
/schedule 2022-06-06T04:30:00+09:00
> Mapの旧URLを削除する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/minio.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/argocd-helm-chart-values.yaml
Grafanaでリソースの利用状況を見ていじったほうがよさそうなRequestsをいじった
> Adjust memory based on usage

- seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
Podがどんどん増えてきたのもあるのでホストのメモリに余裕があるので上げておく
> increase k8s worker vm memory

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/redisbungee-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redisbungee-redis.yaml
Prometheus rule specがないって怒られてた
> Add bungeeredis

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/redisbungee-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redisbungee-redis.yaml
> specify lb ip and resource requests

- seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
SAN Segment経由でホストしている共有ストレージだとcontrol-plane上にいるetcdのパフォーマンスが低下したのでローカルディスクにお引越しする
> feat: vm-diskはローカルでホストする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
- terraform/onp_cluster_namespaces.tf
> remove sentry resources

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/loki.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/minio.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/redis/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/redis/redisbungee-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redis/bungeesemaphore-redis.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/redis/redisbungee-redis.yaml
> remove security context

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cert-manager/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/moco/kustomization.yaml
MySQL OperatorのMOCOと、依存関係にあるcert-managerを入れる
> Add MOCO and cert-manager

- seichi-onp-k8s/cluster-boot-up/scripts/nodes/k8s-node-setup.sh
> mod feature-gates DelegateFSGroupToCSIDriver=false

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/scaled-object.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/service-monitor.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/stateful-set.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
> Kagawa in prd

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
> feat: 1day の難易度を normal にする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/scaled-object.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/stateful-set.yaml
https://redmine.seichi.click/issues/11219
* サバイバルモードとして行動可能な時間は変わらず
* 起動時間のうち、以前の時間以外はスペクテイターモード
* 香川の起動時間を23.5時間/日に変更
> 香川のワールドをスペクテイターで見れるようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichi-game-data-server/deployment.yaml
おそらくアップデート内容は以下。
* 依存関係のアップデート多数
* https://github.com/GiganticMinecraft/seichi-game-data-server/pull/53
* https://github.com/GiganticMinecraft/seichi-game-data-server/pull/54
* https://github.com/GiganticMinecraft/seichi-game-data-server/pull/73
> fix: update seichi-game-data-server

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
> kagawa を bump + 1day の StatefulSet で 1day 専用のイメージを利用するようにする

- seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/deployment.yaml
> Update BungeeCord Exporter

- seichi-onp-k8s/manifests/seichi-kubernetes/kustomize-bases/minecraft-gateway-bungeecord/configs/plugin-configs.yaml
↓にしたがって設定を変える
https://github.com/weihao/bungeecord-prometheus-exporter/blob/7f72951142a02d5c62a9671399106c0e8a655db5/src/main/resources/config.json
https://github.com/weihao/bungeecord-prometheus-exporter#notes
> modify exporter config

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/synology-csi-storageclass/kustomization.yaml
ref. https://github.com/SynologyOpenSource/synology-csi/issues/30#issuecomment-1418654617
> update synology csi

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/metallb/metallb-address-pool.yaml
```
2: ens18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
link/ether ae:ba:0f:0e:67:e3 brd ff:ff:ff:ff:ff:ff
altname enp0s18
inet 192.168.8.21/20 brd 192.168.15.255 scope global ens18
valid_lft forever preferred_lft forever
inet6 fe80::acba:fff:fe0e:67e3/64 scope link
valid_lft forever preferred_lft forever
```
> Fix MetalLB Config

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
ref. https://grafana.com/grafana/dashboards/18015-cilium-policy-verdicts/
> add cilium verdicts

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/root/projects.yaml
> add more ns

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/metrics-server/kustomization.yaml
ref. https://github.com/kubernetes-sigs/metrics-server/releases
> update metrics server

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/newrelic.yaml
> feat: newrelicの送信データ量を減らす

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
https://grafana.com/grafana/plugins/isovalent-hubble-datasource/
> hubble metrics

- docker-images/mod-downloader/Dockerfile
```
$  ls -lh
total 16368
-rw-r--r--  1 inductor  staff   673B May  6 12:11 Dockerfile
-rw-r--r--  1 inductor  staff   861B Apr 14 15:23 go.mod
-rw-r--r--  1 inductor  staff   4.5K Apr 14 15:23 go.sum
-rw-r--r--  1 inductor  staff   1.4K Feb  7 11:02 main.go
-rwxr-xr-x  1 inductor  staff   8.0M May  6 12:12 mod-downloader
$  ls -lh
total 12368
-rw-r--r--  1 inductor  staff   657B May  6 12:10 Dockerfile
-rw-r--r--  1 inductor  staff   861B Apr 14 15:23 go.mod
-rw-r--r--  1 inductor  staff   4.5K Apr 14 15:23 go.sum
-rw-r--r--  1 inductor  staff   1.4K Feb  7 11:02 main.go
-rwxr-xr-x  1 inductor  staff   6.0M May  6 12:11 mod-downloader
```
> Minify build

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#map-roles
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#map-roles-using-teams
> grafana map role

- docker-images/mod-downloader/Dockerfile
> change base image

- .gitignore
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mariadb/mariadb.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
- terraform/onp_cluster_secrets.tf
> Prepare minecraft mariadb

- terraform/cloudflare_page_rules.tf
closes #1094
文脈: Auto minify が JS を壊していた https://github.com/GiganticMinecraft/seichi_infra/issues/1094#issuecomment-1599150661
> Cloudflare Auto Minify を JS について切る

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichi-portal-backend/deployment.yaml
ref https://github.com/GiganticMinecraft/seichi-portal-backend/pkgs/container/seichi-portal-backend
> update portal backend

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/pyroscope-ebpf.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/pyroscope.yaml
> install pyroscope

- docker-images/mcservers/base-server-image/common-plugin-list.ini
> chore(deps): bump Spigot plugin DiscordSRV to 1.26.2

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
ref. https://github.com/cilium/hubble-ui/issues/321#issuecomment-1571891834
> fix hubble ui issue

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
> feat: 1 day to reset の Docker Image を更新

- README.md
- terraform/README.md
> docs: Terraform に関する詳細なドキュメントを書く

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/reloader/kustomization.yaml
https://github.com/stakater/Reloader/issues/482#issuecomment-1653353996
> no submodule

- seichi-onp-k8s/cluster-boot-up/ansible/README.md
- seichi-onp-k8s/cluster-boot-up/ansible/ansible.cfg
- seichi-onp-k8s/cluster-boot-up/ansible/clusterwide.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/hosts/k8s-servers/inventory
- seichi-onp-k8s/cluster-boot-up/ansible/roles/01-ssh-keygen/tasks/main.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/roles/02-setup-sshd-config/tasks/main.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/roles/11-kubeadm-join-cp/tasks/main.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/roles/12-kubeadm-join-wk/tasks/main.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/roles/21-copy-kubeconfig/tasks/main.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/roles/requirements.yaml
- seichi-onp-k8s/cluster-boot-up/ansible/site.yaml
- seichi-onp-k8s/cluster-boot-up/scripts/nodes/k8s-node-setup.sh
- seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
> feat: ansibleによるクラスターブートアップの簡略化

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/idea-reaction-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
Discord Bot [idea-reaction](https://github.com/GiganticMinecraft/idea-reaction) を稼働させる Pod を追加します.
- [redmine #13459](https://redmine.seichi.click/issues/13459)
> feat: idea-reaction の Pod を追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/mariadb/mariadb.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mariadb/mariadb.yaml
Reverts GiganticMinecraft/seichi_infra#1459
> Revert "Update prom/mysqld-exporter Docker tag to v0.15.0"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/stateful-set.yaml
サーバーのバージョンを変えるのとmod-downloaderを最新のものにする
> サーバーのバージョンを1.18.2に変える

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
mod-downloaderとサーバー側で同じvolumeをマウントして、minioからプラグインがダウンロードされるようにする
> mod-downloaderにvolumeをマウントする

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/mariadb/mariadb.yaml
- terraform/onp_cluster_secrets.tf
https://discord.com/channels/237758724121427969/959299646725951580/1185790540055335013
これをやりました
> feat: DBのinitContainerで本番環境のダンプファイルを取得して適用する

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
> すべてのワールドにkeepInventoryを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
> elytraプラグインのconfigのインデントを直す

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
今のデバッグ環境では必要ないのと、 https://discord.com/channels/237758724121427969/1186694359320633523 のようなプラグイン起因で起こっていると考えられる不具合があるため削除しました
> ViaVersionとViaBackwardsを削除

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
permissionの追加と一部追加忘れの日本語訳を追加しました
> 保護を消すことのできる権限とClickTpaのconfigの変更

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
https://discord.com/channels/237758724121427969/1186323105149362396/1186323105149362396
https://redmine.seichi.click/issues/10133
> fix: ホッパーの輸送速度を変更

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
https://discord.com/channels/237758724121427969/1185939484211163267/1187933010197221407
> feat: add WorldGuard config

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
`/rtp`コマンドを提供するためのプラグインを1.18対応したので追加しました。
> RandomTeleportプラグインを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
https://discord.com/channels/237758724121427969/1186684039059484774/1188792404174712892
多分これの原因です
> chore: worldGuardのblock-other-explosionsをfalseに変える

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
Reverts GiganticMinecraft/seichi_infra#1649
> Revert "cilium 1.15 rc"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
`world`から`world_2`に変わったのでそれに合わせました
> fix: WorldGuardの設定のフォルダ名を直す

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/plugin-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
メインサーバー用のOriginSpawnのconfigを追加しました
> メインサーバーにOriginSpawnのconfigを入れる

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
OriginSpawnのconfigを追加するときにvolumeの追加を忘れていたので追加しました
> fix: volumeを追加

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
https://discord.com/channels/237758724121427969/1185973673971155057 を解決するためのフラグです
> エンダードラゴンをスポーンさせないフラグを設定

- terraform/onp_cluster_argocd.tf
Reverts GiganticMinecraft/seichi_infra#1792
> Revert "chore(deps): update helm release argo-cd to v6"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
Reverts GiganticMinecraft/seichi_infra#1812
> Revert "chore: デバッグ環境をpaperからspigotに戻す"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
> 正しくコメントアウトで来てなかったのでコメントアウトし直す

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
ワールドマイグレーションで`OutOfMemoryError`が発生するのでPaper公式が推奨しているJVMのフラグを追加しました
> paper公式が推奨するjvm optionを追加する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/minio.yaml
Reverts GiganticMinecraft/seichi_infra#1871
> Revert "chore(deps): update helm release minio to v5.1.0"

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
> refactor: 存在しないワールドに対して保護のフラグ設定をしていたので削除

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
Reverts GiganticMinecraft/seichi_infra#1909
> Revert "chore(deps): update helm release cilium to v1.15.2"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
https://community.synology.com/enu/forum/1/post/155938
> synologyのLUNIDは1スタートらしい

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
> fix: seichiassist-downloaderのパスを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
Update to [idea-reaction v0.2.0](https://github.com/GiganticMinecraft/idea-reaction/releases/tag/v0.2.0)
> deps: bump idea-reaction v0.2.0

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-snmp-exporter.yaml
Reverts GiganticMinecraft/seichi_infra#1862
> Revert "chore(deps): update helm release prometheus-snmp-exporter to v5"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
Reverts GiganticMinecraft/seichi_infra#1930.
ref. https://github.com/GiganticMinecraft/idea-reaction/issues/57
> Revert "deps: bump idea-reaction v0.2.0"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
> chore: LuckParmsをminioから落とすように変更する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1948
> Revert "Revert "chore: replicasを0にする""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1949
> Revert "Revert "Revert "chore: replicasを0にする"""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1950
> Revert "Revert "Revert "Revert "chore: replicasを0にする""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1951
> Revert "Revert "Revert "Revert "Revert "chore: replicasを0にする"""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1952
> Revert "Revert "Revert "Revert "Revert "Revert "chore: replicasを0にする""""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1953
> Revert "Revert "Revert "Revert "Revert "Revert "Revert "chore: replicasを0にする"""""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1954
> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "chore: replicasを0にする""""""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#1955
> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "chore: replicasを0にする"""""""""

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/argo-events-reverse-proxy.yaml
argo-workflowsにwebhookを飛ばせるように、POST専用のリバースプロキシの定義を追加しました
https://discord.com/channels/237758724121427969/959299646725951580/1231007863883829401
> argo-workflows用のリバースプロキシを定義する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/argo-workflows-reverse-proxy.yaml
> feat: argo-wf-proxy 用の Service を定義する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/idea-reaction-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/common-configs/kustomization.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
- bump idea-reaction v0.2.3: https://github.com/GiganticMinecraft/idea-reaction/releases/tag/v0.2.3
- remove unused config
> deps: bump idea-reaction v0.2.3

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
`debug-pr-2115-s1` がエラーになっている原因である `world-downloader` を一度コメントアウトします (404エラーになっていて起動に失敗している)
ref: https://canary.discord.com/channels/237758724121427969/959299646725951580/1266620141932777562
> fix: Comment out the world data fetch

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
- terraform/main.tf
- terraform/onp_cluster_secrets.tf
https://github.com/GiganticMinecraft/idea-reaction/releases/tag/v0.3.0
> deps: bump idea-reaction v0.3.0

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/cilium-networking/bgp-peering-policy.yaml
Reverts GiganticMinecraft/seichi_infra#2151
> Revert "fix address definition"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/cilium.yaml
Reverts GiganticMinecraft/seichi_infra#2145
> Revert "Update Cilium"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite.yaml
`volumes` や `containers` などの定義が間違っていたので修正
> fix: babyrite pod の定義エラーを修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite-config.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/babyrite/babyrite.yaml
babyrite v0.10.0 に更新します. コンフィグの設定内容が追加されたため設定も更新しました
https://babyrite.m1sk9.dev/changelog.html#v0100
- https://github.com/m1sk9/babyrite/pull/205 で引用メッセージのメンションを無効化できるようになりました. ここでは `false` に設定しメンションを無効化しています.
- https://github.com/m1sk9/babyrite/pull/207 で JSON 方式のログが出力されるようになりました. 整地鯖で使用している Grafana Loki に合わせて `json` と設定しています.
> deps: bump babyrite v0.10.0

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/idea-reaction/idea-reaction.yaml
Reverts GiganticMinecraft/seichi_infra#2176
> Revert "chore(deps): update ghcr.io/giganticminecraft/idea-reaction docker tag to v0.5.0"

- terraform/main.tf
- terraform/onp_cluster_secrets.tf
> chore: Fix idea-reaction prefix and region

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/argo-workflows-reverse-proxy.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/event-source.yaml
* プロキシの所在はサービスの場所に揃えるべき
* Webhook側でURL持たせてると疎通に問題がありそうなので消してみる
> modify webhook

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
Reverts GiganticMinecraft/seichi_infra#2193
関係なかったので Revert
> Revert "fix: 使っていない parameter を削除"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
Reverts GiganticMinecraft/seichi_infra#2195
> Revert "fix: dataKey から body. を削除"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
https://github.com/5GZORRO/issm/blob/ffaf2121f6c35399554eddb1a925985bae17f80e/sensors/issm-domain-aux-sensor-v2.yaml を参考にして書き換えてみました
> fix: parameter の取得先を変える

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/seichiassist-downloader/sensor.yaml
Reverts GiganticMinecraft/seichi_infra#2210
関係なかったので revert します
> Revert "fix: download-seichiassist に entrypoint を追加"

- docker-images/mcservers/debug/seichi-servers/base-images/1_18_2/Dockerfile
Reverts GiganticMinecraft/seichi_infra#2404
全然関係なかったので戻します
> Revert "Revert "chore(deps): update ghcr.io/giganticminecraft/seichi_minecraft_server_base:1.0.0-java17-jdk docker digest to 627736a""

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/mcserver-configs.yaml
close [SeichiAssist-ExternalLib#192](https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/192)
> feat: add `/hub` command

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
close [GiganticMinecraft/SeichiAssist-ExternalLibs#192](https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/192)
> fix: fix hub name in BungeeHubCommand

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
ref. https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/189
> feat: add region-grid-fitter config

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
ref https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/186
> feat: add StreamClock config

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
Reverts #2446
Close https://github.com/GiganticMinecraft/SeichiAssist-ExternalLib/issues/190
動作確認が済んだので、テスト用に追加したメッセージを削除
> テスト用に追加したtceのメッセージを削除

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
seichi_infra に乗っていないプラグイン設定を追加します．TradeSystem の翻訳ファイルについては日本語版がないため，プラグイン側にコントリビュートした上でこちらに後ほど追加します．
> feat: Add more plugin configs

- terraform/onp_cluster_argocd.tf
- terraform/onp_cluster_minecraft_secrets.tf
- terraform/onp_cluster_namespaces.tf
- terraform/onp_cluster_secrets.tf
Reverts GiganticMinecraft/seichi_infra#2473
> Revert "一時的にK8sリソースを消す"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mariadb/mariadb.yaml
Reverts GiganticMinecraft/seichi_infra#2480
関係なかったので revert します
> Revert "fix: mariadb の設定に bind-address の設定を追加"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-operator.yaml
Use https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-68x-to-69x
> Upgrade prometheus operator config

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
> deps: Update 1day-to-reset stateful set

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/deployment.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
revert #2517 
SwiftMOTD を MagicMOTD に置き換えます．
> feat: Replace SwiftMOTD to MagicMOTD

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/minecraft-gateway-bungeecord/deployment.yaml
> fix: Fix ArgoCD error

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
> fix: Fix motd

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
> fix: Fix motd style

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/luckperms-permission-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
ref GiganticMinecraft/SeichiAssist-ExternalLib#191
> LuckPermsの権限設定をIaC管理する

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/luckperms-permission-configs.yaml
> fix: quote asterisk in yaml

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/luckperms-permission-configs.yaml
> fix: fix typo

- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/common-configs/plugin-configs.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/app-templates/seichi-debug-minecraft-on-seichiassist-pr/templates/debug-s1/seichiassist.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
> Revert ObserverUtils configs

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/redisbungee-redis.yaml
Reverts GiganticMinecraft/seichi_infra#2577
> Revert "fix: redisbungee-redis の auth.usePasswordFiles を false にする"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-minecraft/mcserver--debug-s1/stateful-set.yaml
https://github.com/GiganticMinecraft/seichi_infra/pull/2622 と同じであとで revert します
> chore: update minecraft server debug base

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mariadb/coreprotect-db.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mariadb/litebans-db.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- terraform/onp_cluster_minecraft_secrets.tf
> s1 サーバーのイメージを更新

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
https://github.com/GiganticMinecraft/seichi_infra/pull/2668
> fix: volumeClaimTemplates で name を明示的に指定する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/stateful-set.yaml
> fix: s2~7 の volumeClaimTemplates フィールドを明示的に指定する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
base-image に組み込まれている config が追加されていない？っぽいので追加します。
> fix: s1 サーバーの copy_plugins_src に /plugins を追加する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#2697
変わらなかったので revert します
> Revert "fix: s1 サーバーの copy_plugins_src に /plugins を追加する"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
#2697 と順番を変えてみました
この環境変数を追加する前までは動いていたので、この環境変数の設定が悪さをしているのは間違いなさそうな気がしています
> chore: copy_plugins_src に /plugins ディレクトリを追加

- renovate.json
> chore: renovate に seichi_minecraft_server_production のイメージを検知させる

- docker-images/mcservers/base-server-image/Dockerfile
- docker-images/mcservers/base-server-image/common-plugin-list.ini
MODS_FILE オプションが指定されていると競合して動かない
> fix: REMOVE_OLD_MODES オプションが動かないのを修正

- docker-images/mcservers/debug/seichi-servers/base-images/1_12_2/Dockerfile
- docker-images/mcservers/debug/seichi-servers/base-images/1_18_2/Dockerfile
- docker-images/mcservers/debug/seichi-servers/individual-images/deb-s1/Dockerfile
- docker-images/mcservers/debug/seichi-servers/individual-images/deb-s2/Dockerfile
- docker-images/mcservers/production/kagawa/Dockerfile
- docker-images/mcservers/production/kagawa/additional-plugin-list.ini
- docker-images/mcservers/production/lobby/Dockerfile
- docker-images/mcservers/production/lobby/additional-plugin-list.ini
- docker-images/mcservers/production/one-day-to-reset/Dockerfile
- docker-images/mcservers/production/one-day-to-reset/additional-plugin-list.ini
- docker-images/mcservers/production/seichi-servers/common-image/Dockerfile
related to: https://github.com/GiganticMinecraft/seichi_infra/pull/2854
> fix: base-server-image を使う Dockerfile からプラグインリストの定義ファイルを取り除く

- docker-images/mcservers/production/seichi-servers/common-image/additional-plugin-configs/SeichiAssist/config.yml
https://discord.com/channels/237758724121427969/1366613724554596453/1366613724554596453
> fix: SeichiAssistのグリッド式保護のユニット数が現行とあっていないので修正

- renovate.json
```
Regex matching
A valid regex pattern:
Starts with / or !/
Ends with / or /i
```
https://docs.renovatebot.com/string-pattern-matching/
> chore(renovate): fix regex

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
https://discord.com/channels/237758724121427969/1368931000708759633/1368931000708759633
https://minecraft.fandom.com/ja/wiki/%E3%83%95%E3%82%A1%E3%83%B3%E3%83%88%E3%83%A0
https://redmine.seichi.click/issues/13670
> 整地ワールドにてファントムがスポーンしないようにする

- .github/workflows/build_mcserver_images.yaml
- docker-images/mcservers/production/seichi-servers/individual-images/s1/Dockerfile
- docker-images/mcservers/production/seichi-servers/individual-images/s2/Dockerfile
- docker-images/mcservers/production/seichi-servers/individual-images/s3/Dockerfile
- docker-images/mcservers/production/seichi-servers/individual-images/s5/Dockerfile
- docker-images/mcservers/production/seichi-servers/individual-images/s7/Dockerfile
- docker-images/mcservers/production/seichi-servers/individual-images/votelistener/Dockerfile
ref. #782
※関係ないイメージのタグにもつけるようになっていますが、まあそれは一旦そういうものということで...。
> 各本番サーバのイメージ内に含まれる`common`イメージのタグを固定する

- .github/workflows/build_mcserver_images.yaml
This reverts commit 4296dd96b4e905b8d1c072475bccf5e4afd39cc7, reversing changes made to a91f54fa251fefbe6854b93c9755c3106bea076e.
> revert: "Merge pull request #2956 from GiganticMinecraft/Lucky3028-patch-1

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--kagawa/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--one-day-to-reset/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--votelistener/stateful-set.yaml
> StatefulSet中の本番サーバのイメージタグ更新とダイジェストの削除

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/minio.yaml
> chore: minio のボリュームサイズを 10Gi にする

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/https-exits.yaml
> fix: update internal authority for proxmox to correct IP address

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/stateful-set.yaml
> chore: mcserver の statefulset の定義順を変える

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#3080
> Revert "chore: lobby サーバー内のディレクトリを確認するためのコンテナを追加"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/stateful-set.yaml
サーバー公開時にマージしてください
Reverts GiganticMinecraft/seichi_infra#3050
> Revert "chore: lobby サーバーのホワイトリストを有効にする"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/stateful-set.yaml
Reverts GiganticMinecraft/seichi_infra#3134
> Revert "chore: anti-proxy の whitelist/blacklist ファイルを minio の別のバケットから持ってくるようにする"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--lobby/argo-workflows-backup.yaml
> fix(schedule): update backup CronWorkflow to run at 2 AM every Monday

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/argo-workflows-backup.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/argo-workflows-backup.yaml
> fix: delete-coreprotect-s... を step に含める

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s1/workflow-sa.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s2/workflow-sa.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s3/workflow-sa.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/workflow-sa.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s7/workflow-sa.yaml
> fix: データベース CRD を削除する用の権限をサービスアカウントに付与する

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/workflows/mcserver-backup/workflow-template.yaml
https://argo-workflows.readthedocs.io/en/latest/walk-through/dag/
> fix: workflow-template で dag の指定形式が間違っていたのを直す

- docker-images/mcservers/production/seichi-servers/individual-images/s3/Dockerfile
> feat: add SHA256sum for base image in s3 image

- docker-images/mcservers/production/seichi-servers/common-image/additional-plugin-configs/SpectatorTheater/config.yml
https://discord.com/channels/237758724121427969/959300687072722945/1058748429947379792
> fix: SpectatorTheaterの設定が足りなかったので修正

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config.yaml
Reverts GiganticMinecraft/seichi_infra#3438
> Revert "fix: debungeecord-config の kind を configmap にする"

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/cloudflared-tunnel-exits/http-exits.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/bugsink/deployment.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/bugsink/service.yaml
- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mariadb/bugsink.yaml
- terraform/main.tf
- terraform/onp_cluster_minecraft_secrets.tf
[Bugsink](https://www.bugsink.com/) は Sentry SDK 互換のバグトラッキングツールです。
参考: https://github.com/bugsink/deployment-contrib/tree/main/manifests
> Bugsink を追加

- docker-images/mcservers/production/seichi-servers/common-image/common-minecraft-server-configs/server.properties
#3653 の変更は、baseではなくてcommonにされるべきでした
> fix: fix `simulation-distance` in common server image

- seichi-onp-k8s/manifests/seichi-kubernetes/apps/seichi-minecraft/mcserver--s5/stateful-set.yaml
> chore: update s5 image
